/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedShoppingListRouteImport } from './routes/_authenticated/shopping-list'
import { Route as AuthenticatedRecipesRouteImport } from './routes/_authenticated/recipes'
import { Route as AuthenticatedPricesRouteImport } from './routes/_authenticated/prices'
import { Route as AuthenticatedPreferencesRouteImport } from './routes/_authenticated/preferences'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as ApiPublicHooksWeeklyPricesRouteImport } from './routes/api/public/hooks/weekly-prices'
import { Route as ApiPublicHooksImportTickRouteImport } from './routes/api/public/hooks/import-tick'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedShoppingListRoute =
  AuthenticatedShoppingListRouteImport.update({
    id: '/shopping-list',
    path: '/shopping-list',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRecipesRoute = AuthenticatedRecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPricesRoute = AuthenticatedPricesRouteImport.update({
  id: '/prices',
  path: '/prices',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPreferencesRoute =
  AuthenticatedPreferencesRouteImport.update({
    id: '/preferences',
    path: '/preferences',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicHooksWeeklyPricesRoute =
  ApiPublicHooksWeeklyPricesRouteImport.update({
    id: '/api/public/hooks/weekly-prices',
    path: '/api/public/hooks/weekly-prices',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksImportTickRoute =
  ApiPublicHooksImportTickRouteImport.update({
    id: '/api/public/hooks/import-tick',
    path: '/api/public/hooks/import-tick',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app': typeof AuthenticatedAppRoute
  '/preferences': typeof AuthenticatedPreferencesRoute
  '/prices': typeof AuthenticatedPricesRoute
  '/recipes': typeof AuthenticatedRecipesRoute
  '/shopping-list': typeof AuthenticatedShoppingListRoute
  '/api/public/hooks/import-tick': typeof ApiPublicHooksImportTickRoute
  '/api/public/hooks/weekly-prices': typeof ApiPublicHooksWeeklyPricesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app': typeof AuthenticatedAppRoute
  '/preferences': typeof AuthenticatedPreferencesRoute
  '/prices': typeof AuthenticatedPricesRoute
  '/recipes': typeof AuthenticatedRecipesRoute
  '/shopping-list': typeof AuthenticatedShoppingListRoute
  '/api/public/hooks/import-tick': typeof ApiPublicHooksImportTickRoute
  '/api/public/hooks/weekly-prices': typeof ApiPublicHooksWeeklyPricesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/_authenticated/preferences': typeof AuthenticatedPreferencesRoute
  '/_authenticated/prices': typeof AuthenticatedPricesRoute
  '/_authenticated/recipes': typeof AuthenticatedRecipesRoute
  '/_authenticated/shopping-list': typeof AuthenticatedShoppingListRoute
  '/api/public/hooks/import-tick': typeof ApiPublicHooksImportTickRoute
  '/api/public/hooks/weekly-prices': typeof ApiPublicHooksWeeklyPricesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/app'
    | '/preferences'
    | '/prices'
    | '/recipes'
    | '/shopping-list'
    | '/api/public/hooks/import-tick'
    | '/api/public/hooks/weekly-prices'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app'
    | '/preferences'
    | '/prices'
    | '/recipes'
    | '/shopping-list'
    | '/api/public/hooks/import-tick'
    | '/api/public/hooks/weekly-prices'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/app'
    | '/_authenticated/preferences'
    | '/_authenticated/prices'
    | '/_authenticated/recipes'
    | '/_authenticated/shopping-list'
    | '/api/public/hooks/import-tick'
    | '/api/public/hooks/weekly-prices'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicHooksImportTickRoute: typeof ApiPublicHooksImportTickRoute
  ApiPublicHooksWeeklyPricesRoute: typeof ApiPublicHooksWeeklyPricesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/shopping-list': {
      id: '/_authenticated/shopping-list'
      path: '/shopping-list'
      fullPath: '/shopping-list'
      preLoaderRoute: typeof AuthenticatedShoppingListRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recipes': {
      id: '/_authenticated/recipes'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof AuthenticatedRecipesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prices': {
      id: '/_authenticated/prices'
      path: '/prices'
      fullPath: '/prices'
      preLoaderRoute: typeof AuthenticatedPricesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/preferences': {
      id: '/_authenticated/preferences'
      path: '/preferences'
      fullPath: '/preferences'
      preLoaderRoute: typeof AuthenticatedPreferencesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/weekly-prices': {
      id: '/api/public/hooks/weekly-prices'
      path: '/api/public/hooks/weekly-prices'
      fullPath: '/api/public/hooks/weekly-prices'
      preLoaderRoute: typeof ApiPublicHooksWeeklyPricesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/import-tick': {
      id: '/api/public/hooks/import-tick'
      path: '/api/public/hooks/import-tick'
      fullPath: '/api/public/hooks/import-tick'
      preLoaderRoute: typeof ApiPublicHooksImportTickRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
  AuthenticatedPreferencesRoute: typeof AuthenticatedPreferencesRoute
  AuthenticatedPricesRoute: typeof AuthenticatedPricesRoute
  AuthenticatedRecipesRoute: typeof AuthenticatedRecipesRoute
  AuthenticatedShoppingListRoute: typeof AuthenticatedShoppingListRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRoute,
  AuthenticatedPreferencesRoute: AuthenticatedPreferencesRoute,
  AuthenticatedPricesRoute: AuthenticatedPricesRoute,
  AuthenticatedRecipesRoute: AuthenticatedRecipesRoute,
  AuthenticatedShoppingListRoute: AuthenticatedShoppingListRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicHooksImportTickRoute: ApiPublicHooksImportTickRoute,
  ApiPublicHooksWeeklyPricesRoute: ApiPublicHooksWeeklyPricesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
